version: "3.2"

services:
  main:
    image: openjdk:18
    container_name: 'main-app-spring'
    ports:
      - 8182:8080 # Inner/External
    environment:
      RABBIT_HOST: queue
    links:
      - queue
    networks:
      - app
  queue:
    image: rabbitmq:3.8-management
    container_name: 'queue-rabbitmq'
    ports:
        - 5672:5672 #JMS Port
        - 15672:15672 #Management Port - default user:pass = guest:guest
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - app
  processor:
    container_name: 'processor-golang'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@message-broker:5672/
    restart: always
    depends_on:
      - queue
    networks:
      - app

networks:
  app:
    driver: bridge