version: "3.2"

services:
  springboot:
    image: openjdk:18
    container_name: 'springboot'
    ports:
      - 8182:8080
    environment:
      RABBIT_HOST: rabbitmq
    links:
      - rabbitmq
    networks:
      - app
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672 #JMS Port
        - 15672:15672 #Management Port - default user:pass = guest:guest
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - app

networks:
  app:
    driver: bridge