version: "3.2"

services:
  # main:
  #   image: openjdk:18
  #   container_name: 'main-app-spring'
  #   ports:
  #     - 8182:8080 # Inner/External
  #   environment:
  #     RABBIT_HOST: queue
  #   links:
  #     - queue
  #   networks:
  #     - app
  queue:
    image: rabbitmq:3.8-management
    container_name: 'queue-rabbitmq'
    ports:
        - 5672:5672 #JMS Port
        - 15672:15672 #Management Port - default user:pass = guest:guest
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - app
  processor:
    container_name: 'processor-golang'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@queue
    links:
      - queue
      - db
    depends_on:
      - queue
      - db
    restart: on-failure
    networks:
      - app
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
    - app

volumes:
  db:
    driver: local

networks:
  app:
    driver: bridge